### ISSUE TITLE
NegativeArraySizeException in PStringType

### ISSUE THREAD

**Issue by charles-jacobsen** [j256/simplemagic#24]
This test:

```
// Trigger (failed match for) the Digital Symphony
// sound sample (RISC OS) pattern:
byte[] x = new byte[] {
    0x2, 0x1, 0x13, 0x13, 0x13, 0x01, 0x0d, 0x10,
    0x1,
    // pstring: first byte is length. Can't do
    // do unsigned bytes in Java, so to do 
    // length of 255, use -1.
    -1, 0x1, 0x1, 0x1
};

ContentInfoUtil util = new ContentInfoUtil();
util.findMatch(x);
```

generates this exception:

> java.lang.NegativeArraySizeException
    at com.j256.simplemagic.types.PStringType.extractValueFromBytes(PStringType.java:23)
    at com.j256.simplemagic.entries.MagicEntry.matchBytes(MagicEntry.java:149)
    at com.j256.simplemagic.entries.MagicEntry.matchBytes(MagicEntry.java:185)
    at com.j256.simplemagic.entries.MagicEntry.matchBytes(MagicEntry.java:68)
    at com.j256.simplemagic.entries.MagicEntries.findMatch(MagicEntries.java:150)
    at com.j256.simplemagic.entries.MagicEntries.findMatch(MagicEntries.java:138)
    at com.j256.simplemagic.ContentInfoUtil.findMatch(ContentInfoUtil.java:207)

I think the issue is that in PStringType, the string length is read as a signed byte.

**Comment by j256** [comment]
Wow.  Bad bug.  Fixed in https://github.com/j256/simplemagic/commit/dfb87a4dcbb8a047c4f0310c1a80a4b6151156f7 .  Just pushed out version 1.12 to fix it.  Thanks much.

**Comment by charles-jacobsen** [comment]
Thanks for the quick turn-around!
