### ISSUE TITLE
ArrayOutOfBoundsException on exe

### ISSUE THREAD

**Issue by epastoor** [j256/simplemagic#30]
I'm attempting to get the content type of an exe file (putty.exe) and it is throwing an ArrayIndexOutOfBoundsException. I can't upload putty.exe as it is not supported. It is downloadable here: https://the.earth.li/~sgtatham/putty/latest/w64/putty.exe

`2017-08-23 16:46:29 ERROR 1503521189293246 RequestUtils.java:994 Simple Magic error during detection java.lang.ArrayIndexOutOfBoundsException: -5
	at com.j256.simplemagic.endian.LittleEndianConverter.convertNumber(LittleEndianConverter.java:40)
	at com.j256.simplemagic.endian.LittleEndianConverter.convertNumber(LittleEndianConverter.java:16)
	at com.j256.simplemagic.types.NumberType.extractValueFromBytes(NumberType.java:48)
	at com.j256.simplemagic.entries.MagicEntry.matchBytes(MagicEntry.java:140)
	at com.j256.simplemagic.entries.MagicEntry.matchBytes(MagicEntry.java:181)
	at com.j256.simplemagic.entries.MagicEntry.matchBytes(MagicEntry.java:181)
	at com.j256.simplemagic.entries.MagicEntry.matchBytes(MagicEntry.java:66)
	at com.j256.simplemagic.entries.MagicEntries.findMatch(MagicEntries.java:128)
	at com.j256.simplemagic.entries.MagicEntries.findMatch(MagicEntries.java:122)
	at com.j256.simplemagic.ContentInfoUtil.findMatch(ContentInfoUtil.java:258)`

I am calling this using: 
`
private static final ContentInfoUtil CONTENT_TYPE_DETECTOR_SIMPLE_MAGIC = new ContentInfoUtil();
ContentInfo info = CONTENT_TYPE_DETECTOR_SIMPLE_MAGIC.findMatch(fileItem.get());`

I am using version 1.12

**Comment by j256** [comment]
Huh.  As far as I can see the byte[] array is protected going high so maybe offset is negative?  I've added better protections there.

**Comment by epastoor** [comment]
Your guess was right. 

I debugged this a little. In this case, here are the values:
int offset = -5
int size = 1
int bytes.length = 854072

**Comment by epastoor** [comment]
Will your fix go with 1.13?

**Comment by j256** [comment]
Awesome information.  Thanks for it.  Yes it will go into 1.13.

**Comment by j256** [comment]
Here's the commit with the new code: 
https://github.com/j256/simplemagic/commit/fbd10af3e13597c8d9b16c572a4d05119bc5cb6f

**Comment by d-biswas** [comment]
I had the same issue. When is the tentative release date of 1.13

**Comment by j256** [comment]
1.13 has been released.
