### ISSUE TITLE
ContentInfoUtil.findMatch([77, 90]) generates NPE

### ISSUE THREAD

**Issue by jcalcote** [j256/simplemagic#78]
We're using j256/simplemagic version 1.14 in a project and we noticed an NPE with the following call stack when attempting to find a match on a 2-byte prefix where the byte array is [77, 90] (hex [4d, 5a]):

```
java.lang.NullPointerException
        at com.j256.simplemagic.entries.MagicEntry.matchBytes(MagicEntry.java:134) ~[simplemagic-1.14.jar:?]
        at com.j256.simplemagic.entries.MagicEntry.matchBytes(MagicEntry.java:181) ~[simplemagic-1.14.jar:?]
        at com.j256.simplemagic.entries.MagicEntry.matchBytes(MagicEntry.java:66) ~[simplemagic-1.14.jar:?]
        at com.j256.simplemagic.entries.MagicEntries.findMatch(MagicEntries.java:128) ~[simplemagic-1.14.jar:?]
        at com.j256.simplemagic.entries.MagicEntries.findMatch(MagicEntries.java:122) ~[simplemagic-1.14.jar:?]
        at com.j256.simplemagic.ContentInfoUtil.findMatch(ContentInfoUtil.java:253) ~[simplemagic-1.14.jar:?]
```

This file is a 2-byte truncated windows executable.

**Comment by j256** [comment]
This seems to be already fixed @jcalcote .  The following test does not fail for me.

	byte[] x = { 77, 90 };
	ContentInfoUtil util = new ContentInfoUtil();
	util.findMatch(x);
